field.widget.settings.zilker_address:
  type: field.widget.settings.address_default
  label: 'Zilker address widget settings'
  mapping:
    require_zilker:
      type: boolean
      label: 'Require Zilker address'
